// Helper file to make coverage work for all dart files
// **************************************************************************
// Because of this: https://github.com/flutter/flutter/issues/27997#issue-410722816
// DO NOT EDIT THIS FILE USE: sh scripts/import_files_coverage.sh YOUR_PACKAGE_NAME
// **************************************************************************

// ignore_for_file: unused_import
import 'package:mirai/page/video/video_detail_card.dart';
import 'package:mirai/page/video/video_detail_page.dart';
import 'package:mirai/page/feeds/feeds_repo.dart';
import 'package:mirai/page/feeds/item/video_item_view.dart';
import 'package:mirai/page/feeds/article_info.dart';
import 'package:mirai/page/main/main_page.dart';
import 'package:mirai/routes.dart';
import 'package:mirai/pages.dart';
import 'package:mirai/main.dart';
import 'package:mirai/labeled_checkbox.dart';
import 'package:mirai/login_widget.dart';
import 'package:mirai/account_model.dart';
import 'package:mirai/model/video/video_detail_info.dart';
import 'package:mirai/model/video/video_detail_repo.dart';
import 'package:mirai/model/proto/oidb_0xb57.pb.dart';
import 'package:mirai/model/proto/kd_wns_proxy.pbjson.dart';
import 'package:mirai/model/proto/oidb_0x68b.pbenum.dart';
import 'package:mirai/model/proto/kd_tools_tab.pbenum.dart';
import 'package:mirai/model/proto/account_login.pbjson.dart';
import 'package:mirai/model/proto/article_summary.pb.dart';
import 'package:mirai/model/proto/now_live.pbjson.dart';
import 'package:mirai/model/proto/article_summary.pbjson.dart';
import 'package:mirai/model/proto/feeds_info.pbjson.dart';
import 'package:mirai/model/proto/now_live.pb.dart';
import 'package:mirai/model/proto/feeds_info.pb.dart';
import 'package:mirai/model/proto/oidb_0xb57.pbenum.dart';
import 'package:mirai/model/proto/oidb_0x68b.pb.dart';
import 'package:mirai/model/proto/oidb_0x68b.pbserver.dart';
import 'package:mirai/model/proto/kd_tools_tab.pbserver.dart';
import 'package:mirai/model/proto/oidb_0xb57.pbjson.dart';
import 'package:mirai/model/proto/kd_tools_tab.pb.dart';
import 'package:mirai/model/proto/article_summary.pbenum.dart';
import 'package:mirai/model/proto/account_login.pb.dart';
import 'package:mirai/model/proto/now_live.pbenum.dart';
import 'package:mirai/model/proto/feeds_info.pbenum.dart';
import 'package:mirai/model/proto/kd_wns_proxy.pbserver.dart';
import 'package:mirai/model/proto/article_summary.pbserver.dart';
import 'package:mirai/model/proto/feeds_info.pbserver.dart';
import 'package:mirai/model/proto/kd_wns_proxy.pb.dart';
import 'package:mirai/model/proto/oidb_0x68b.pbjson.dart';
import 'package:mirai/model/proto/account_login.pbserver.dart';
import 'package:mirai/model/proto/kd_tools_tab.pbjson.dart';
import 'package:mirai/model/proto/account_login.pbenum.dart';
import 'package:mirai/model/proto/now_live.pbserver.dart';
import 'package:mirai/model/proto/kd_wns_proxy.pbenum.dart';
import 'package:mirai/model/proto/oidb_0xb57.pbserver.dart';
import 'package:mirai/model/repos.dart';
import 'package:mirai/model/wns.dart';
import 'package:mirai/model/toolstab/tools_tab_repo.dart';
import 'package:mirai/model/toolstab/model.dart';
import 'package:mirai/logni_view_model.dart';
import 'package:mirai/widgets/feed_list.dart';
import 'package:mirai/widgets/page_header.dart';
import 'package:mirai/widgets/feed_list_repo.dart';

void main(){}